# Generated by Django 5.2.5 on 2025-08-25 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255)),
                ('setor_responsavel', models.CharField(max_length=80)),
                ('prioridade', models.CharField(choices=[('low', 'Baixa'), ('mid', 'Média'), ('high', 'Alta')], max_length=5)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('todo', 'A Fazer'), ('doing', 'Em andamento'), ('done', 'Concluído')], default='todo', max_length=10)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='app.usuario')),
            ],
        ),
    ]
